---
config:
  layout: elk
---
flowchart LR
 subgraph STS["Student Tutoring System"]
    direction LR
        login(["login"])
        addManager(["add manager"])
        manageSubjects(["manage subjects"])
        addSubject(["add new subject"])
        deleteSubject(["delete subject"])
        manageTutors(["manage tutors"])
        addTutor(["add new tutor"])
        deleteTutor(["delete tutor"])
        addZoomMeeting(["add zoom meeting"])
        signUp(["sign up"])
        changePassword(["change password"])
        chooseSubject(["choose subject"])
        manageAppointments(["manage appointments"])
        addAppointment(["add appointment"])
        deleteAppointment(["delete appointment"])
        buyCredits([buy credits])
        searchAppointment([search for appointment])
        searchSubject([serch subject])
        searchTutor([search tutor])
        bookAppointment([book appointment])
        bookBySubjectTime([book by subject and time])
        boookByID([book by ID])
        cancelAppointment([cancel appointment])
  end
    Manager["Manager"] --- addManager & manageSubjects & manageTutors
    addManager -. &lt; include &gt; .-> login
    manageSubjects -. &lt; include &gt; .-> login
    manageTutors -. &lt; include &gt; .-> login
    addSubject -. &lt; extend &gt; .-> manageSubjects
    deleteSubject -. &lt; extend &gt; .-> manageSubjects
    addTutor -. &lt; extend &gt; .-> manageTutors
    deleteTutor -. &lt; extend &gt; .-> manageTutors
    addZoomMeeting -. &lt; extend &gt; .-> manageTutors
    addTutor -. &lt; include &gt; .-> createTutorZoomAccount(["create tutor zoom account"])
    Tutor["Tutor"] --- signUp & changePassword & chooseSubject & manageAppointments
    changePassword -. &lt; include &gt; .-> login
    chooseSubject -. &lt; include &gt; .-> login
    manageAppointments -. &lt; include &gt; .-> login
    addAppointment -. &lt; extend &gt; .-> manageAppointments
    deleteAppointment -. &lt; extend &gt; .-> manageAppointments
    Student["Student"] --- signUp & buyCredits & searchAppointment & bookAppointment & cancelAppointment
    buyCredits -. &lt; include &gt; .-> login
    searchAppointment -. &lt; include &gt; .-> login
    bookAppointment -. &lt; include &gt; .-> login
    cancelAppointment -. &lt; include &gt; .-> login
    searchSubject -. &lt; extend &gt; .-> searchAppointment
    searchTutor -. &lt; extend &gt; .-> searchAppointment
    bookBySubjectTime -. &lt; extend &gt; .-> bookAppointment
    boookByID -. &lt; extend &gt; .-> bookAppointment